# Generated by Django 2.1.5 on 2021-05-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('universty', models.CharField(max_length=40)),
                ('fullName', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=40)),
                ('account_type', models.CharField(choices=[('accType1', 'Öğrenci'), ('accType2', 'Akademisyen')], default='accType1', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
