# Generated by Django 2.1.5 on 2021-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='account',
            name='universty',
            field=models.CharField(max_length=250),
        ),
    ]
