# Generated by Django 2.1.5 on 2021-05-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210515_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_avatar',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf ekle'),
        ),
    ]
