# Generated by Django 2.1.5 on 2021-05-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_avatar',
            field=models.FileField(blank=True, default='../static/image/akdenız_logo.png', null=True, upload_to='', verbose_name='Fotoğraf ekle'),
        ),
    ]
