# Generated by Django 2.1.5 on 2021-06-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210527_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_avatar',
        ),
    ]
