# Generated by Django 2.1.5 on 2021-05-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
    ]
