# Generated by Django 2.1.5 on 2021-05-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Habere 2. Fotoğraf veya Video Ekleyiniz.'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Habere 3. Fotoğraf veya Video Ekleyiniz.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Habere Kapak Fotoğrafı Ekleyiniz.'),
        ),
    ]
