# Generated by Django 2.1.5 on 2021-06-12 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0008_news_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='favourite_news',
            field=models.ManyToManyField(blank=True, related_name='favourite_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
