# Generated by Django 2.1.5 on 2021-05-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
