# Generated by Django 2.1.5 on 2021-05-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_sendarticle_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendarticle',
            name='article_image',
        ),
    ]
