# Generated by Django 2.1.5 on 2021-05-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_comment_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye 2. Fotoğraf Ekleyin'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_image3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye 3. Fotoğraf Ekleyin'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye Kapak Fotoğrafı Ekleyin'),
        ),
    ]
