# Generated by Django 2.1.5 on 2021-06-12 11:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20210606_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_image3',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_photo',
        ),
        migrations.RemoveField(
            model_name='sendarticle',
            name='article_type',
        ),
        migrations.AddField(
            model_name='sendarticle',
            name='article_image',
            field=models.FileField(default='', upload_to='', verbose_name='Makale Resimi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makaleye Fotoğraf Ekleyin'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
