# Generated by Django 2.1.5 on 2021-05-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20210521_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journals',
            name='content',
        ),
        migrations.AddField(
            model_name='journals',
            name='journals_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Derginin Dosyasını Ekleyiniz'),
        ),
    ]
