# Generated by Django 2.1.5 on 2021-05-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_auto_20210521_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='journals',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
