# Generated by Django 2.1.5 on 2021-05-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_comment_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='interviews_image2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Röportaj'a 2.Fotoğraf veya Video Ekleyiniz."),
        ),
        migrations.AddField(
            model_name='interviews',
            name='interviews_image3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Röportaj'a 3.Fotoğraf veya Video Ekleyiniz."),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='interviews_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Röportaj'a Kapak Fotoğrafı Ekleyiniz."),
        ),
    ]
